### ISSUE TITLE
Migrate tikui to a node library

### ISSUE THREAD

**Issue by jeremietisserand** [tikui/tikui#10]
Move all `tech` directory to a node independent library (something like `tikui-cli-service`).

Inspiration: @vue/cli principles.

Need @tikui/developers to have more ideas.

**Comment by Gnuk** [comment]
I think we will have `tikui-service` or `tikui-core` or `tikui command` from another repository I'll call `tikui-core` because `tikui-cli` already exists and it's not the same goal.
