### ISSUE TITLE
Tikui logo

### ISSUE THREAD

**Issue by Gnuk** [tikui/tikui#25]
Create Tikui logo, don't hesitate to make propositions.

The goal is also to make a favicon.

**Comment by ImNiki** [comment]
Hi, here is a quick sketch of a logo idea.

![IMG_20191008_102941](https://user-images.githubusercontent.com/2797922/66380690-355c3380-e9b8-11e9-9f46-9439db31b1d6.jpg)

**Comment by Gnuk** [comment]
I prefer the logo who looks like 
![logo-1 svg](https://user-images.githubusercontent.com/1397032/66433076-cadede00-ea1f-11e9-9198-242935b8db15.png)

**Comment by mandyellow** [comment]
Hello, 🦊 I created a logo for your project, hope you like it.

![image](https://user-images.githubusercontent.com/30158643/66867269-9d57de80-efa3-11e9-8be3-0e49269b119d.png)

**Comment by jeremietisserand** [comment]
I really like this logo!

We appreciate your contribution. Do you have a svg version to submit?

**Comment by Gnuk** [comment]
HI @mandyellow , it's just to notify you, I agree, i'm in favor of a SVG version and a favicon.ico if possible :) it's a nice logo idea.

**Comment by nonomoho** [comment]
I like it too! Thank you @mandyellow 😃

**Comment by pascalgrimaud** [comment]
Love it ! So nice !!! Thanks so much @mandyellow !

**Comment by mandyellow** [comment]
Yeah, SVG and favicon are fine for me. Where I can upload it? `/src/logo`''?

**Comment by nonomoho** [comment]
I think `/src/assets/logo` will be great!
I let @Gnuk confirm that.

**Comment by Gnuk** [comment]
You can upload favicon on `src/favicon.ico` by adding a new Pull Request if you want, you can also add the logo on the root directory and link it as an image inside the `README.md` if GitHub can render the svg file inside a README.md. You can also send the file on something like svgur or equivalent and add the link here :)

**Comment by pascalgrimaud** [comment]
@Gnuk : you should change the logo of the organization too
See https://github.com/tikui

**Comment by Gnuk** [comment]
@pascalgrimaud Thank you , it's now done :)
