### ISSUE TITLE
Discussion: Documentation modules

### ISSUE THREAD

**Issue by Gnuk** [tikui/tikui#28]
Hi,

I'm working on #9 and #10 and to achieve this, I have to put `documentation` folder outside `tikui/tikui`.

So to be flexible, I'm working on a standard to make documentation modules, so I propose to have a file inside the root of the tikui project named `tikuiconfig.json` containing the `documentation` module name like it:

```json
{
  "documentation": "tikui"
}
```

Then in this example, `tikui` will be the documentation module, so I have a prefix for each modules, I suggest `tikuidoc`, then the real module name will be `tikuidoc-tikui`, it's why I created the project inside `tikui` group.

I'm working on the module structure to make it easy to use, then you can propose your ideas but you should notice there is a source part for documentation, a template part for `componentDoc` and `templateDoc` structure and we should have a easy way to put public files like css/scss files, images …

Here is the `README.md` I'm working on for `tikuidoc-tikui`:

````md
# Tikui documentation
  
This is the official Tikui documentation module.


## Create a documentation module

If you want to create your own module, please name it `tikuidoc-$MODULE_NAME` where `MODULE_NAME` is the name of your module.

Then you can clone this module as a reference and change files you want (don't forget to change `package.json` to make your style and then you should publish it on the official node package registry using `npm publish`.

## Consume a tikui module

To consume a module, you should install it on your Tikui project using the latest version from `tikui/tikui` and then you have to edit the `tikuiconfig.json` to set the documentation name like your `$MODULE_NAME`.

Here is an example for a module named `tikuidoc-my-custom-module`:

```json
{
  "documentation": "my-custom-module"
}
```

Then you can do exactly what you do with a standard Tikui project.
````

I'm waiting for your suggestions so I notify @tikui/developers for it !

**Comment by jeremietisserand** [comment]
I don't know if we have to force the user to use a prefix.

I would let a `tikuidoc-tikui` as a default choice in the file : 
```json
{
  "documentation": "tikuidoc-tikui"
}
```

**Comment by Gnuk** [comment]
> I don't know if we have to force the user to use a prefix.
> 
> I would let a `tikuidoc-tikui` as a default choice in the file :
> 
> ```json
> {
>   "documentation": "tikuidoc-tikui"
> }
> ```

My idea to this prefix is to search easily a documentation module from node registry like `generator` from yeoman but this can be challenged I think.

**Comment by Gnuk** [comment]
As there is not a lot of discussions here I decided to let you review the PR #29
