### ISSUE TITLE
Some inperfection in the how-to

### ISSUE THREAD

**Issue by sbally** [tikui/tikui#36]
Hi dear contributor,

- You need to add `npm install` before `npm run serve`
- You must specify where add `include:componentDoc(height=55) button/button.md` in the file.
- Please add a introductory sentence before tikui.scss (I create 2 files but I edit another file just after. WTF in my mind) 

Thank for you help.
It's a nice project.

**Comment by nonomoho** [comment]
Thank you to challenge our README.md! 
I understand that for us it's clear in our mind but for others it can be confusing...
