### ISSUE TITLE
Allow to set URL prefix

### ISSUE THREAD

**Issue by Skyfallz** [tikui/tikui#39]
Hi,

Tikui should be able to be prefixed by an optional static baseURL, which would allow URL-based routing in reverse-proxy based architectures, without URL rewriting. At now, we can only rely on domain name, which can be quite blocking in some cases. 

Example :
With baseURL: '/patterns/', 'www.example.org/patterns/index.html' can be easily forwarded to an appropriate backend, with no URL rewriting needed (otherwise it would need to strip the '/patterns/' part in the request to backend).

This would be an interesting feature, especially in dynamics environments (it would allow to mutualise some resources, which can be really appreciated in public cloud projects).

Let me know if you need some more context,

**Comment by Gnuk** [comment]
Now the generated sources are relative since `@tikui/core` 2.0.0 and `tikuidoc-tikui` 4.0.0 are released. So it's totally possible to do this. So I close the issue!
