### ISSUE TITLE
How to manage responsive in iframe ?

### ISSUE THREAD

**Issue by jessyca27** [tikui/tikui#54]
Hello,

I would like to manage responsive with breakpoint (1300px for example) but the iframe is less.

Thanks

**Comment by Gnuk** [comment]
Hi @jessyca27 , you imagine to have a width for the iframe to manage it ?

Currently in chrome the iframe can be resized by dragging the right bottom corner. It may be a workaround before I can add an eventual fix. I add a label to discuss about it with @tikui/developers and anyone else.

**Comment by Gnuk** [comment]
So I forgot to specify in the documentation we can use `templateDoc` and `componentDoc`, I'll close this issue after it is documented.
