### ISSUE TITLE
Create a tikui example app

### ISSUE THREAD

**Issue by jeremietisserand** [tikui/tikui#6]
Create `tikui/tikui-atomic-example`.

Need @tikui/developers ideas for the repository name.

**Comment by jeremietisserand** [comment]
@tikui/developers Does this issue can be closed with the add of the documentation in the README ?

**Comment by hdurix** [comment]
I'm not sure the readme is enough. It would be nice to have a complete app showing an example of a pattern library. It would live alongside the "engine" project.

**Comment by Gnuk** [comment]
Yes, it should be in another repo I think, no ?

**Comment by Gnuk** [comment]
Maybe it's possible to publish an example as a page, may this need to make absolute html references relative before ?

**Comment by Gnuk** [comment]
Done on http://www.tikui.org/documentation.html
