### ISSUE TITLE
Review tikui technical choices

### ISSUE THREAD

**Issue by jeremietisserand** [tikui/tikui#9]
Need @tikui/developers suggestions.

**Comment by Gnuk** [comment]
As a reference in #28 I create a project http://github.com/tikui/tikuidoc-tikui

**Comment by Gnuk** [comment]
I suggest renaming `<component>.template.pug` with `<component>.code.pug` to be less confusing, it's breaking but I think it's better, what do you thing @tikui/developers ?

**Comment by Gnuk** [comment]
So I created #33 for it :)

**Comment by Gnuk** [comment]
As I said on #49 we may have to find a better name for `componentDoc` and `templateDoc` inclusion, I'm waiting your suggestions :)

**Comment by Gnuk** [comment]
As discussed, it's not a really important point, we can take our decision later for the next major version.
